### ISSUE TITLE
Can we have some example results?

### ISSUE THREAD

**Issue by AriFordsham** [qnikst/ghc-timings-report#4]
I would love some representative benchmarks. (With confidential module names removed 😀)

**Comment by qnikst** [comment]
Hello, I've made an example for the HaskellNet package https://github.com/qnikst/ghc-timings-report/tree/master/report-example not the most interesting package, but there was nothing confidential. Does that work for you?

**Comment by AriFordsham** [comment]
Yes, thank you!
I just wanted to see, out of acedemic interest, where GHC typically spends it's time, without getting the whole thing set up. That's given me (and hopefully others) something to chew on.

**Comment by qnikst** [comment]
From my practice, it heavily depends on the program. However, in my experience (that doesn't include much GHC hacking) tracking coercisions when using generics can be improved a lot, it looks like there must be low hanging fruits as well as very measurable improvements. But in order to track the changes, you'll need more involved tools that will dig into GHC internals. Like some sort of tracing or the last work on the GHC profiling. So it's better to consult with GHC team :)
